spring:
  datasource:
    url: jdbc:dm://192.168.1.54:5236
    username: CAPP
    password: glaway123
    driver-class-name: dm.jdbc.driver.DmDriver
    # flyway 配置
  flyway:
    # 启用或禁用 flyway
    enabled: true
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration/**/*.sql
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: flyway_schema_history
    # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
    # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baseline-on-migrate: true
      # 字符编码 默认 UTF-8
    encoding: UTF-8
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    clean-disabled: true
      # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    out-of-order: false
      # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
    validate-on-migrate: true
    placeholder-replacement: false

